$base           = rgb(000000)
$surface        = rgb(404040)
$overlay        = rgb(404040)
$muted          = rgb(888888)
$subtle         = rgb(aaaaaa)
$text           = rgb(c1c1c1)
$love           = rgb(5f8787)
$gold           = rgb(8c7f70)
$rose           = rgb(aaaaaa)
$pine           = rgb(9b8d7f)
$foam           = rgb(888888)
$iris           = rgb(999999)

$mauve = $iris
$flamingo = $love
$blue = $foam
$green = $pine
$yellow = $gold
$red = $love
$sky = $foam
$sapphire = $pine
$lavender = $subtle
$subtext0 = $subtle
$subtext1 = $muted
