$base           = rgb(282828)
$surface        = rgb(32302f)
$overlay        = rgb(504945)
$muted          = rgb(928374)
$subtle         = rgb(a89984)
$text           = rgb(ebdbb2)
$love           = rgb(cc241d)
$gold           = rgb(d79921)
$rose           = rgb(fb4934)
$pine           = rgb(98971a)
$foam           = rgb(458588)
$iris           = rgb(b16286)

$mauve = $iris
$flamingo = $rose
$blue = $foam
$green = $pine
$yellow = $gold
$red = $love
$sky = $foam
$sapphire = $pine
$lavender = $subtle
$subtext0 = $subtle
$subtext1 = $muted
